#!/bin/bash -x

path=$PWD;

sudo yum update -y&&sudo yum install git -y&&cd /&&sudo curl -o .gitignore https://raw.githubusercontent.com/secobau/linux/master/Scripts/rootfs.gitignore&&sudo git init&&sudo git add .&&sudo git commit -m "Initial commit";

cd $path;

sudo cp mgmt.hosts /etc/hosts;

for x in client httpd httpd-php nginx;
do ssh $x hostname;done;

for x in client httpd httpd-php nginx;
do ssh $x 'sudo yum update -y&&sudo yum install git -y&&cd /&&sudo curl -o .gitignore https://raw.githubusercontent.com/secobau/linux/master/Scripts/rootfs.gitignore&&sudo git init&&sudo git add .&&sudo git commit -m "Initial commit"';done;

for x in client httpd httpd-php nginx;
do for y in hosts;
do for z in /etc;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in client httpd httpd-php mgmt nginx;
do for y in firewall;
do for z in /usr/local/sbin;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in client httpd httpd-php mgmt nginx;
do for y in firewall;
do for z in /usr/local/sbin;
do ssh $x "sudo chmod +x $z/$y";done;done;done

for x in client httpd httpd-php mgmt nginx;
do for y in firewall.service;
do for z in /etc/systemd/system;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in client httpd httpd-php nginx;
do for y in firewall.service;
do ssh $x "sudo systemctl daemon-reload;sudo systemctl enable $y;sudo systemctl restart $y";done;done;

for x in client httpd httpd-php nginx;
do ssh $x 'sudo yum install -y elinks';done;

for x in client httpd httpd-php nginx;
do for y in my.cnf;
do for z in /etc;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in client httpd httpd-php mgmt nginx;
do for y in sysctl.conf;
do for z in /etc;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in client;
do for y in sysctl.conf;
do for z in /etc;
do ssh $x "sudo yum install -y httpd-tools&&sudo sed -i /swappiness/s/100/0/ $y $z/$y";done;done;done

for x in client;
do for y in 99-$x.conf;
do for z in /etc/security/limits.d;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in httpd httpd-php nginx;
do for y in build.project.props;
do scp $y $x:;ssh $x "sed -i '/project.url.base/s/^project.url.base.*$/project.url.base = http:\/\/'$(grep $x$ mgmt.hosts|cut -d' ' -f1)/ $y";done;done;

for x in httpd httpd-php;
do ssh $x 'sudo yum install -y httpd&&sudo systemctl enable httpd';done;

for x in httpd httpd-php nginx;
do ssh $x 'sudo yum -y update&&sudo wget https://centos7.iuscommunity.org/ius-release.rpm&&sudo amazon-linux-extras install epel -y&&sudo yum -y install ius-release.rpm&&sudo yum -y update&&sudo sed -i /enabled/s/0/1/ /etc/yum.repos.d/ius-archive.repo&&sudo yum -y install php56u php56u-mysqlnd.x86_64&&sudo sed -i /memory_limit/s/128/1024/ /etc/php.ini&&wget https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm&&sudo yum install mysql80-community-release-el7-3.noarch.rpm -y&&sudo yum-config-manager --disable mysql80-community&&sudo yum-config-manager --enable mysql56-community&&sudo yum install mysql-community-server.x86_64 -y&&sudo systemctl enable mysqld;';done;

for x in httpd nginx;
do ssh $x 'sudo yum -y install php56u-fpm&&sudo systemctl enable php-fpm;';done;

for x in nginx;
do ssh $x 'sudo amazon-linux-extras install nginx1.12 -y&&sudo systemctl enable nginx;';done;

for x in httpd nginx;
do for y in php-fpm.conf;
do for z in /etc;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in httpd nginx;
do for y in www.conf;
do for z in /etc/php-fpm.d;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in httpd httpd-php;
do for y in httpd.conf;
do for z in /etc/httpd/conf;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in httpd;
do for y in 00-mpm.conf;
do for z in /etc/httpd/conf.modules.d;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in nginx;
do for y in nginx.conf;
do for z in /etc/nginx;
do scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";done;done;done;

for x in httpd httpd-php nginx;
do ssh $x 'ssh-keygen -P "" -f $HOME/.ssh/id_rsa&&echo&&echo $x&&cat .ssh/id_rsa.pub;';done;
read -p "Please upload the previous SSH public key to your Github repository to proceed and press ENTER when ready" ENTER;

for x in httpd httpd-php nginx;
do ssh $x 'sudo yum -y install git&&git clone git@github.com:ec-europa/devco-reference.git&&rm -rf $HOME/devco-reference/.git&&cp $HOME/build.project.props $HOME/devco-reference&&sudo yum install -y composer&&cd $HOME/devco-reference&&composer install&&sudo systemctl restart mysqld&&./toolkit/phing  build-platform&&cd $HOME/devco-reference&&./toolkit/phing build-subsite-dev&&./toolkit/phing install-clone&&cd build&&../toolkit/drush rr&&../toolkit/drush cc all;';done;

for x in client httpd httpd-php mgmt nginx;
do ssh $x 'sudo yum update -y&&cd /&&sudo git add .&&sudo git commit -m "Final setup"';done;

for x in client httpd httpd-php nginx;
do ssh $x 'sudo init 6';done;

sudo init 6
