#!/bin/bash -x

path=$PWD;

cd $path

for x in client;
do ssh $x hostname;done

for x in client;
do ssh $x 'sudo yum update -y&&sudo yum install git -y&&cd /&&sudo curl -o .gitignore https://raw.githubusercontent.com/secobau/linux/master/Scripts/rootfs.gitignore&&sudo git init&&sudo git add .&&sudo git commit -m "Initial commit"';done;

for x in client;
do echo $x;scp firewall firewall.service $x:;ssh $x 'sudo chown root. firewall*;sudo chmod +x firewall;sudo mv firewall /usr/local/sbin;sudo mv firewall.service /etc/systemd/system;sudo systemctl daemon-reload;sudo systemctl enable firewall.service';done;

for x in client;
do scp $x.hosts $x:hosts;ssh $x 'sudo mv hosts /etc';done

for x in client;
do scp $x.firewall $x:firewall;ssh $x 'sudo chown root. firewall&&sudo chmod +x firewall&&sudo mv firewall /usr/local/sbin&&sudo systemctl restart firewall.service';done

for x in client;
do ssh $x 'sudo yum install -y elinks';done

for x in client;
do scp my.cnf $x:;ssh $x 'sudo chown root. my.cnf&&sudo cp my.cnf /etc';done

for x in client;
do scp sysctl.conf $x:;ssh $x 'sudo chown root. sysctl.conf&&sudo cp sysctl.conf /etc';done
sudo cp sysctl.conf /etc&&sudo chown root. /etc/sysctl.conf

for x in client;
do ssh $x 'sudo yum install -y httpd-tools&&sudo sed -i /swappiness/s/100/0/ sysctl.conf /etc/sysctl.conf';done

for x in client;
do ssh $x 'sudo yum update -y&&cd /&&sudo git add .&&sudo git commit -m "Final setup"';done;

for x in client;
do ssh $x 'sudo init 6';done
