#!/bin/bash -x

function scp_cp_chown
{
scp $x.$y $x:$y;ssh $x "sudo cp $y $z&&sudo chown root. $z/$y";
}

path=$PWD;

cd $path;

for x in nginx;
do ssh $x 'rm -rf $HOME/devco-reference/.git&&cp $HOME/build.project.props $HOME/devco-reference&&sudo yum install -y composer&&cd $HOME/devco-reference&&composer install&&sudo systemctl restart mysqld&&./toolkit/phing  build-platform&&cd $HOME/devco-reference&&./toolkit/phing build-subsite-dev&&./toolkit/phing install-clone&&cd build&&../toolkit/drush rr&&../toolkit/drush cc all;';done;

for x in nginx;
do ssh $x 'sudo yum update -y&&cd /&&sudo git add .&&sudo git commit -m "Final setup"';done;

for x in nginx;
do ssh $x 'sudo init 6';done;
